## DAY-11

In [1]:
import pandas as pd
import numpy as np

In [2]:
a=np.array([20,45,2,1,8,5,51,484,8,48,484,8,89])

In [3]:
a

array([ 20,  45,   2,   1,   8,   5,  51, 484,   8,  48, 484,   8,  89])

In [4]:
a[-5:-12:-1]

array([  8, 484,  51,   5,   8,   1,   2])

In [5]:
a.ndim

1

In [6]:
b=np.random.randint(45,70,(7,8))
b

array([[62, 67, 60, 53, 49, 57, 56, 52],
       [51, 69, 63, 53, 55, 58, 61, 63],
       [48, 54, 59, 50, 58, 67, 67, 68],
       [48, 68, 63, 68, 55, 65, 64, 58],
       [61, 48, 52, 54, 51, 51, 56, 68],
       [48, 64, 48, 51, 62, 56, 48, 64],
       [67, 67, 52, 65, 64, 46, 48, 68]])

In [7]:
b[-4]  #It is used to access the elements of a row

array([48, 68, 63, 68, 55, 65, 64, 58])

In [8]:
b.ndim

2

In [9]:
b[-1]  #It will directly access the row itself not the elements

array([67, 67, 52, 65, 64, 46, 48, 68])

In [10]:
b[:,4]  #It is used to acces the elemts of a separate column

array([49, 55, 58, 55, 51, 62, 64])

In [11]:
b[1:3]  #Access the elements of a row from 1:3

array([[51, 69, 63, 53, 55, 58, 61, 63],
       [48, 54, 59, 50, 58, 67, 67, 68]])

The line `np.random.seed(4)` is used in Python to set the seed for NumPy's random number generator. Here's a breakdown of what it means:

- **`np.random`** refers to the random module in the NumPy library, which provides functions to generate random numbers, such as `np.random.rand()`, `np.random.randint()`, etc.
  
- **`seed(4)`** sets the "seed" of the random number generator to the value `4`. A seed is an initial value used to initialize the random number generation algorithm. By setting a specific seed (in this case, `4`), you ensure that the sequence of random numbers generated will be the same every time the code is run. This is useful for reproducibility, as you can guarantee that the "random" values will be consistent across different runs of the program.

In summary, `np.random.seed(4)` makes sure that any random numbers generated by `np.random` in the subsequent code will be the same every time you run the program, as long as the seed remains the same.

In [12]:
np.random.seed(4)
b=np.random.randint(45,78,(7,8))
b

array([[50, 46, 68, 53, 54, 75, 48, 45],
       [66, 66, 54, 47, 75, 53, 47, 68],
       [77, 77, 73, 48, 60, 76, 62, 62],
       [70, 54, 57, 68, 75, 67, 48, 56],
       [68, 51, 52, 54, 63, 66, 75, 60],
       [72, 53, 53, 77, 75, 49, 56, 53],
       [76, 62, 59, 54, 49, 48, 49, 51]])

In [13]:
b[:,3] #gets 3 rd col

array([53, 47, 48, 68, 54, 77, 54])

In [14]:
b[1,3]  #prints the 1st columns 3rd element

47

In [15]:
b[5,6]  #5th row 6th column element

56

In [16]:
b[2]  #gets 2nd row

array([77, 77, 73, 48, 60, 76, 62, 62])

In [17]:
b

array([[50, 46, 68, 53, 54, 75, 48, 45],
       [66, 66, 54, 47, 75, 53, 47, 68],
       [77, 77, 73, 48, 60, 76, 62, 62],
       [70, 54, 57, 68, 75, 67, 48, 56],
       [68, 51, 52, 54, 63, 66, 75, 60],
       [72, 53, 53, 77, 75, 49, 56, 53],
       [76, 62, 59, 54, 49, 48, 49, 51]])

In [18]:
b[2][1:6]  #Prints the elements of 2nd row and from pos 1:6

array([77, 73, 48, 60, 76])

In [19]:
b[2,1:6]

array([77, 73, 48, 60, 76])

 ## syntax for the  accessing
 array[row_start:row_end:row_step_size]

In [20]:
b

array([[50, 46, 68, 53, 54, 75, 48, 45],
       [66, 66, 54, 47, 75, 53, 47, 68],
       [77, 77, 73, 48, 60, 76, 62, 62],
       [70, 54, 57, 68, 75, 67, 48, 56],
       [68, 51, 52, 54, 63, 66, 75, 60],
       [72, 53, 53, 77, 75, 49, 56, 53],
       [76, 62, 59, 54, 49, 48, 49, 51]])

In [21]:
b[1:6]   #skips the rows 1 and 6 and prints

array([[66, 66, 54, 47, 75, 53, 47, 68],
       [77, 77, 73, 48, 60, 76, 62, 62],
       [70, 54, 57, 68, 75, 67, 48, 56],
       [68, 51, 52, 54, 63, 66, 75, 60],
       [72, 53, 53, 77, 75, 49, 56, 53]])

In [22]:
b[1:6:2]  #skips all the rows in the previous which are of step size=2

array([[66, 66, 54, 47, 75, 53, 47, 68],
       [70, 54, 57, 68, 75, 67, 48, 56],
       [72, 53, 53, 77, 75, 49, 56, 53]])

In [23]:
b[1:6:2,]

array([[66, 66, 54, 47, 75, 53, 47, 68],
       [70, 54, 57, 68, 75, 67, 48, 56],
       [72, 53, 53, 77, 75, 49, 56, 53]])

 ## Syntax for accessing the particular elements using slicing
    array[row_start:row_end:row_step_size,col_start:col_end:col_step_size]

In [24]:
b[1:6:2,1:6]

array([[66, 54, 47, 75, 53],
       [54, 57, 68, 75, 67],
       [53, 53, 77, 75, 49]])

In [25]:
b[1:6:2,1:6:2]

array([[66, 47, 53],
       [54, 68, 67],
       [53, 77, 49]])

In [26]:
b

array([[50, 46, 68, 53, 54, 75, 48, 45],
       [66, 66, 54, 47, 75, 53, 47, 68],
       [77, 77, 73, 48, 60, 76, 62, 62],
       [70, 54, 57, 68, 75, 67, 48, 56],
       [68, 51, 52, 54, 63, 66, 75, 60],
       [72, 53, 53, 77, 75, 49, 56, 53],
       [76, 62, 59, 54, 49, 48, 49, 51]])

In [27]:
b[2:5]

array([[77, 77, 73, 48, 60, 76, 62, 62],
       [70, 54, 57, 68, 75, 67, 48, 56],
       [68, 51, 52, 54, 63, 66, 75, 60]])

In [28]:
b[2:5,2:7]  ##prints 2row 5 col and in that 2 row 7 col

array([[73, 48, 60, 76, 62],
       [57, 68, 75, 67, 48],
       [52, 54, 63, 66, 75]])

In [29]:
b

array([[50, 46, 68, 53, 54, 75, 48, 45],
       [66, 66, 54, 47, 75, 53, 47, 68],
       [77, 77, 73, 48, 60, 76, 62, 62],
       [70, 54, 57, 68, 75, 67, 48, 56],
       [68, 51, 52, 54, 63, 66, 75, 60],
       [72, 53, 53, 77, 75, 49, 56, 53],
       [76, 62, 59, 54, 49, 48, 49, 51]])

In [30]:
b[1:6:2,1:9:3]  #used to access the elements which are mentioned above

array([[66, 75, 68],
       [54, 75, 56],
       [53, 75, 53]])